### PR TITLE
Adding OpenShift templates. Issue #13

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Also I am not sure from which branch I should use the templates. So I have used from master.

**Comment by praveenkumar** [comment]
@LalatenduMohanty I think we have to contact openshift-dev team about using proper branch/tag for those templates instead directly from master.

**Comment by praveenkumar** [comment]
@hferentschik any idea about which tag/branch we should use for templates or directly use `master`?

**Comment by hferentschik** [comment]
> any idea about which tag/branch we should use for templates or directly use master?

Which templates? They come from multiple sources. And no, I don't know either which would be the right tag to use. Using `master` seems wrong, since that's asking for trouble down the road (provided you are using URLs).

If we cannot get a tag, I'd rather download the JSON for the verified templates we use and then during provisioning import from file.

**Comment by LalatenduMohanty** [comment]
> If we cannot get a tag, I'd rather download the JSON for the verified templates we use and then during provisioning import from file.

+1, will update the PR

**Comment by LalatenduMohanty** [comment]
@hferentschik @praveenkumar The latest PR have local copy of the templates

**Comment by praveenkumar** [comment]
@LalatenduMohanty Instead using `/opt/adb/openshift-template` as directory better we use `/opt/adb/openshift/template` because we want `/opt/adb` organized as `/opt/adb/<service_artifacts>` . Other than that we have test this patch.

**Comment by LalatenduMohanty** [comment]
@praveenkumar agree. I have updated the patch and will also test it out.

**Comment by praveenkumar** [comment]
@LalatenduMohanty  did you get time to test those template out or you want me to do single round of testing before approving this PR?

**Comment by praveenkumar** [comment]
@LalatenduMohanty Alright I did a test on this PR and looks like if I use any template it will not start project build anymore, have to find what causing this issue.
- start openshift service
- oc login -u openshift-dev -p devel
- oc new-project foo
- oc new-app nodejs-example  => This step should trigger a build but it's not happening (try without this patch and you will get to know.)

**Comment by praveenkumar** [comment]
@LalatenduMohanty So after spending some time to figure out what else we need, looks like we also have to include imagestream json without that it will not trigger (I am going to read more about S2I stuff) but you have to include https://gist.github.com/praveenkumar/adb8574290517dbc363e in this PR as file name `image-streams-rhel7.json`

**Comment by LalatenduMohanty** [comment]
@praveenkumar Yes, I tested the PR and was facing the same issue where  the build was failing because of same issue with imagestream. However previously there are two image streams and I am not sure if one is enough for us.

```
# Image streams
    https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-rhel7.json
    https://raw.githubusercontent.com/jboss-openshift/application-templates/${ose_tag}/jboss-image-streams.json
```

**Comment by hferentschik** [comment]
For what it is worth, I have been facing similar issues. Hence why I said, it is so important that we double check the templates we include and also minimize them in order to put less work onto our side to make sure things keep working. 

I think one problem here is that one of the files we add defines an image stream we need, but also adds new templates we don't necessarily need. At least that's what I seem to remember from when I was looking at this last. IMO these json files we are using are partly too entangled or maybe better not granular enough. 

Last but not least, I think there is also a bug or at least a usability issue from the OpenShift side here. Apparently one can configure a job and start it, but if a required image stream is not available it just sits there and won't do anything. Really, there should be almost an instant error message. Maybe we could extract some sort of test scenario and open an issue with the OpenShift team?

**Comment by praveenkumar** [comment]
> I think one problem here is that one of the files we add defines an image stream we need, but also adds new templates we don't necessarily need. At least that's what I seem to remember from when I was looking at this last. 

Yes, If you check builder json file content then it consist different builders and that what add those templates (Actually those are builder templates). @LalatenduMohanty already put different application templates after  discussion on ML and I just created a builder template gist (https://gist.github.com/praveenkumar/adb8574290517dbc363e) which only content those builder definition which we care about.

> IMO these json files we are using are partly too entangled or maybe better not granular enough. 

Agree.

> If a required image stream is not available it just sits there and won't do anything. Really, there should be almost an instant error message. 

Instant error message pop up when you try to do a manual build for a app and image stream not available.

> Maybe we could extract some sort of test scenario and open an issue with the OpenShift team? 

Make sense +1

**Comment by hferentschik** [comment]
> Yes, If you check builder json file content then it consist different builders and that what add those templates (Actually those are builder templates). @LalatenduMohanty already put different application templates after discussion on ML and I just created a builder template gist (https://gist.github.com/praveenkumar/adb8574290517dbc363e) which only content those builder definition which we care about.

Nice. The only issue is of course that it means more work for us, since we cannot just include/consume these resources from somewhere. We need to hand-roll them. But I don't see another alternative either atm.

**Comment by LalatenduMohanty** [comment]
@hferentschik @praveenkumar the issue in using selective imagestreams only required for the examples we are including is that an application developer has to add other imagestreams if he/she wants to run other types of applications. Example : In the templates we have not included Python application ( #13) , so as per above discussion we should not include imagestreams for Python. But if an user wants to run a Python application, the image stream would be missing. IMO that is a bad experience for a developer.  

@praveenkumar  https://gist.github.com/praveenkumar/adb8574290517dbc363e does not have image stream information for jboss-eap64-openshift which is required for eap64-mysql-persistent-s2i

**Comment by LalatenduMohanty** [comment]
@praveenkumar @hferentschik IMO we should include alll generic image streams i.e. Python, Ruby, nodejs, php and then include the examples as per #13

**Comment by praveenkumar** [comment]
@LalatenduMohanty If we do that then we also have different builder templates on User dashboard. Don't you think it will confuse?

**Comment by LalatenduMohanty** [comment]
@praveenkumar Not sure what you mean. But isn't it the default behavior i.e. having generic templates for Python, Ruby etc?  from an OpenShift installation.

**Comment by praveenkumar** [comment]
@LalatenduMohanty those are only image streams templates not application specific. if you check https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-rhel7.json (origin file) you can see image stream is tagged with `registry.access.redhat.com` and upstream user who want to use latest image from `docker.io` or from any other registry then he should create his own image builder template and we should only provide default for our existing templates. Hope that makes it little clear.

**Comment by LalatenduMohanty** [comment]
@praveenkumar I can see https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json too. Now we need to figure out how to do it? Looks like the CentOS one fits in ADB and the rhel one in CDK.

**Comment by LalatenduMohanty** [comment]
@praveenkumar Or do we want to merge this PR and then track the issue of how to manage Image stream separately?

**Comment by praveenkumar** [comment]
> @praveenkumar Or do we want to merge this PR and then track the issue of how to manage Image stream separately? 

Yes, lets do that. We will create another issue for manage image stream.

**Comment by praveenkumar** [comment]
LGTM.

**Comment by LalatenduMohanty** [comment]
@praveenkumar created issue https://github.com/projectatomic/adb-utils/issues/87

**Pull request merged**
