### PR TITLE
Fix #13 had typo with image stream

### LINKED ISSUE #13: OpenShift templates should be packaged and available from stock Vagrantbox
This help to address the issue where an application developer should be able setup OpenShift in CDK/ADB and run one template without connecting to internet.

### PR DESCRIPTION
**Pull request by praveenkumar**
This will fix for https://github.com/projectatomic/openshift2nulecule/issues/52  for now. we still have one more issue #87 to evaluate other streams to added.

### CODE REVIEW

**Comment by surajssd** [comment]
@praveenkumar this fixes o2n#52 right, I don't need to raise it again?

**Comment by praveenkumar** [comment]
@surajssd yes that correct, can you please try that out.

step you have to follow for ADB.
- vagrant up --no-provision --provider virtualbox
- vagrant ssh
- vi /opt/adb/openshift/openshift_provision (update this specific line as per patch)
- sccli openshift
- Deploy your app

**Comment by bexelbie** [comment]
Pending feedback from @surajssd - LGTM

**Comment by kadel** [comment]
I've tested this. 
After steps described by @praveenkumar I deployed  MLB Parks example  (`oc new-app https://raw.githubusercontent.com/gshipley/openshift3mlbparks/master/mlbparks-template.json`), build and deployment was successful.
:+1:

**Comment by surajssd** [comment]
@praveenkumar worked nicely for me! So now I can use `sccli` extensively right, without having to provision different VMs for different providers?

**Comment by praveenkumar** [comment]
@surajssd yes it will work with `sccli`.

**Pull request merged**
