### PR TITLE
Fix #20 (Add cert generation script to utils instead having it in kickstart file)

### LINKED ISSUE #20: Add cert generation script to utils instead having it in kickstart file
Currently cert generation script which used by adbinfo is part of kickstart file. As per our effort we can include it in adb-utils repo and include it in rpm.

### PR DESCRIPTION
**Pull request by praveenkumar**
cert generation file should be part of adb-utils instead of base64 in kickstart file.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
LGTM . @praveenkumar we need a PR in https://github.com/projectatomic/adb-atomic-developer-bundle/ to remove the script. We should merge this, once you send a PR to adb

**Comment by LalatenduMohanty** [comment]
https://github.com/projectatomic/adb-atomic-developer-bundle/pull/227  is the equivalent PR in ADB

**Comment by praveenkumar** [comment]
@LalatenduMohanty https://github.com/projectatomic/adb-atomic-developer-bundle/pull/227 here you go.

**Comment by LalatenduMohanty** [comment]
@praveenkumar merged

**Pull request merged**
