### PR TITLE
Fix #86 and #152 Metrics support for openshift

### LINKED ISSUE #86: ELK logging or metrics
Currently we don't have any ELK (ElasticSearch Logging) or metrics (like hawkular) enabled which will be good for developer experience.

### PR DESCRIPTION
**Pull request by praveenkumar**
This patch will enable metrics support for OpenShift.

### CODE REVIEW

**Comment by brgnepal** [comment]
Documentation also need to be added IMO to reflect this change otherwise how user will come to know?

**Comment by praveenkumar** [comment]
@budhrg This is still in discussion and I think doc for this should be part of adb-developer-bundle repo.

**Comment by brgnepal** [comment]
@praveenkumar How I can verify it?

**Comment by praveenkumar** [comment]
@budhrg you can use http://paste.fedoraproject.org/382051/41667214/ Vagrantfile to verify it. 

**Note:** You’ll need to access the hawkular endpoint and accept it’s self signed certificate to see metrics in the pods.

**Comment by LalatenduMohanty** [comment]
@praveenkumar closing the PR as this is not relevant in current context. Please reopen if you think otherwise.

**Pull request closed without merging**
