### PR TITLE
Fix spec file after doc migration from rst to adoc

### PR DESCRIPTION
**Pull request by praveenkumar**
Spec file fix due to doc changes

### CODE REVIEW

**Comment by praveenkumar** [comment]
@LalatenduMohanty @budhrg please review required changes.

**Comment by LalatenduMohanty** [comment]
@praveenkumar please add changelog to the spec file for the change.

**Comment by praveenkumar** [comment]
@LalatenduMohanty Please have a look.

**Comment by LalatenduMohanty** [comment]
LGTM.

**Pull request merged**
