### PR TITLE
Add os jenkins templates

### PR DESCRIPTION
**Pull request by tnozicka**
part of issue #111

### CODE REVIEW

**Comment by tnozicka** [comment]
@LalatenduMohanty You have added the previous templates. Can you please review this PR? Thanks.

**Comment by tnozicka** [comment]
@bparees Please, take a look

**Comment by bparees** [comment]
@tnozicka not sure what i'm reviewing here... they look like the templates from the origin repo, anything beyond that you need me to weigh in on?

**Comment by tnozicka** [comment]
waiting for resolution on https://github.com/openshift/origin/pull/9008

**Comment by tnozicka** [comment]
> @tnozicka not sure what i'm reviewing here... they look like the templates from the origin repo, anything beyond that you need me to weigh in on?

@bparees this was ment mainly before you published https://github.com/openshift/origin/pull/8973 to merge it into origin. These templates were created by me merging your template from ML and the old template from origin. I used diff to your PR(https://github.com/openshift/origin/pull/8973) and it's almost the same with the exception this is based on the newer old Jenkins template (https://github.com/openshift/origin/pull/8919). And I wanted your opinion about security/permissions which is now tracked in https://github.com/openshift/origin/pull/9008.
So I guess, you don't have to review it anymore.

**Comment by praveenkumar** [comment]
Waiting for https://github.com/openshift/origin/pull/9008 to be merged before consumed.

**Comment by tnozicka** [comment]
Also waiting for https://github.com/projectatomic/adb-utils/issues/136

**Comment by tnozicka** [comment]
Waiting for merge https://github.com/projectatomic/adb-utils/pull/138 . I will rebase and finalize this afterwards.

**Comment by tnozicka** [comment]
All dependencies are now merged. Rebased, tested.

@praveenkumar @LalatenduMohanty Please take a look.

**Comment by praveenkumar** [comment]
LGTM.

**Comment by LalatenduMohanty** [comment]
LGTM

**Pull request merged**
