### PR TITLE
Fix #24 Only restart docker if needed

### LINKED ISSUE #24: Only restart docker if needed
We shouldn't be restarting docker [here](https://github.com/projectatomic/adb-utils/blob/cfc3e8d14136a4bb7a9fc4b079a8d2847838df28/services/openshift/scripts/docker_config#L32) unless we really need to.

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by navidshaikh** [comment]
LGTM

**Comment by LalatenduMohanty** [comment]
@praveenkumar  I am not sure if the PR fixes the issue. I need to test and discuss

**Comment by LalatenduMohanty** [comment]
We need to fix https://github.com/projectatomic/adb-utils/blob/master/services/openshift/scripts/docker_config  in way that this script can be reused to add new docker registries.  It should check if the registry is already added , if yes -> no restart of docker, if No-> restart docker

**Comment by praveenkumar** [comment]
@LalatenduMohanty Currently it will not have any options but it solve #24 which say we don't have to restart docker when required insecure registry exist. I will put another request for taking options and use this to for new docker registries.

**Comment by LalatenduMohanty** [comment]
@praveenkumar raised https://github.com/projectatomic/adb-utils/issues/43

**Comment by praveenkumar** [comment]
> Will this not repeatedly add 172.30.0.0/16? 

No, before adding `172.30.0.0/16` it have check to find out if `172.30.0.0` already exist and if not then only it will add.

> You are matching everything after "INSECURE_REGISTRY=" and put it into the buffer and then you paste the buffer followed by '--insecure-registry 172.30.0.0\/16 --insecure-registry '. 

Yes that's right.

> If I call this repeatedly I will get multiple 172.30.0.0\/16 entries. Or am I missing something? Why so complicated?

This script is only called by systemd `ExecStartPre` and `if` check prevent it to append multiple entries. If you are talking about using this script and passing options for different insecure registry, that is currently in plan #43

**Pull request merged**
