### PR TITLE
Adding some print statements during "sccli openshift". Fixes #126

### LINKED ISSUE #126: "sccli openshift" should print some information about docker pulls
Currently `sccli openshift` does not print any information during the command execution.  So user does not get any information what is happening during the whole time. As `sccli openshift` takes some time to execute, we should give information to user about things it is doing in the back end.

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Fixes #126 
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by praveenkumar** [comment]
@LalatenduMohanty I would prefer `stdout` instead of `print` statement if we at all want to show user whats going on if user use it manually.

**Comment by praveenkumar** [comment]
LGTM.

**Comment by praveenkumar** [comment]
@budhrg can you give this change a try with VSM before I merge it?

**Comment by brgnepal** [comment]
@praveenkumar I verified it is not affecting service-manager plugin. Since, at the moment we are showing every data coming from sccli in `--debug` mode. 

LGTM.

**Pull request merged**
