### PR TITLE
Updating to OpenShift Origin images to 1.1.6 tag

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by bexelbie** [comment]
Should we refactor this so that we have a way to specify the version we want in a given build of the ADB via the Kickstart and then if that isn't specified this script provides a default?  That would seem to make builds and version bumps easier to maintain.

**Comment by LalatenduMohanty** [comment]
@bexelbie Actually the version should live https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-openshift-setup/Vagrantfile#L9 .  I will send another PR for that. We are updating here to make it more evident.

**Comment by bexelbie** [comment]
I think we should consider doing both the change you are proposing, @LalatenduMohanty and the change I proposed.  The version fixed in this PR is the default that will be run if you don't pass a version in.  Having that set to a known, recent value, when the box is built and the package is installed is a good thing.  We could then set the default in this script to `latest` which would be a known reasonable option for users who are trying to use sccli directly.

**Comment by LalatenduMohanty** [comment]
@bexelbie latest is not a good solution. It has already broke things once for us https://github.com/projectatomic/adb-utils/pull/120

**Comment by LalatenduMohanty** [comment]
Also I am not in favor of involving ks file for origin version, as keeping it in Vagrantfile makes it more flexible and we can update to a newer version without building the box.

**Comment by bexelbie** [comment]
> Also I am not in favor of involving ks file for origin version, as keeping it in Vagrantfile makes it more flexible and we can update to a newer version without building the box

This is not an either/or situation.  I believe we should have the Version in the Vagrantfile.  That belief has nothing to do with this PR.

I also believe that we should have a sensible default in `sccli` (this PR).  One option is to do as we are doing now where we periodically change that default.  Another option is to set `sccli` to default to "latest" and then set the actual default we want for each build of the ADB in the ADB Kickstart.

This gives us a single management point for reproducibility, config, etc.  It is just an idea.  With this idea the only way someone gets "latest" without explicitly asking for is if they install `sccli` by themselves in their own box.  An ADB will always provide a different default.

**Comment by praveenkumar** [comment]
> I also believe that we should have a sensible default in sccli (this PR). One option is to do as we are doing now where we periodically change that default. Another option is to set sccli to default to "latest" and then set the actual default we want for each build of the ADB in the ADB Kickstart.

@bexelbie I like this idea :+1: we can manage those in kickstart and here set `latest` as default which will make it easy to manage. In kickstart we have to add 2 different sed command to update sccli and openshift_options file when we create box and if a user wants use different TAG then we always have `env` variable to set it.

@LalatenduMohanty We already deprecated `sccli.sh` and we are using `sccli.py` so you have to correct PR (I will send another PR of depreciation of sccli.sh) Also you forgot to update `openshift_options` which also should be set as `latest` as @bexelbie suggested.

https://github.com/projectatomic/adb-utils/blob/master/services/openshift/openshift_option

**Comment by LalatenduMohanty** [comment]
@praveenkumar Are you we suggesting we should have "latest" in sccli and/or in kickstart and  a selected version in ADB OpenShift Vagrantfile?

**Comment by bexelbie** [comment]
@LalatenduMohanty I read @praveenkumar as saying we have the following:
- Kickstart: The version we want to use by default in that build of the ADB, 1.1.6 as of today - Used when nothing is specified in the Vagrantfile.  This value is sed-edited into the sccli in ADB.
- sccli: The version to be used by default if all else fails/not an ADB build, "latest" as of today - this value is replaced in an ADB kickstart.
- Vagrantfile: The version that the user wants to use.  Default today is 1.1.6. This is user supplied or managed in the project.

Did I get it right @praveenkumar ?

**Comment by praveenkumar** [comment]
@bexelbie yes, that what I wanted to point  out. checkout https://github.com/projectatomic/adb-atomic-developer-bundle/pull/402 , hope that will make sense.

**Comment by LalatenduMohanty** [comment]
I am working on a different approach. Basically Origin/OSE version  should present in 
- OpenShift Vagrantfile 
- adb_utils/services/openshift/openshift_option (it will be set to latest for ADB)

And the version mentioned in  Vagrantfile always takes precedence. If Vagrantfile does not have any version then version in openshift_option will be taken in to account. 

Currently we have a bug where if an user starts OpenShift using Vagrantfile , then get in to the box using `vagrant ssh`  , stops and starts OpenShift using `SCCLI` then user will get the OpenShift with version mentioned in the `sccli.py`. This PR should fix that too.

We also need to change Makefile to change the OSE version in `openshift_options` instead of `sccli.py` for downstream . The current code in Makefile is as below.

```
# Changes to sccli for downstream
        sed -i -e \
            "s|^DOCKER_REGISTRY =\(\s\+\)\(.*\)$ |DOCKER_REGISTRY = \"registry\.access\.redhat\.com\"|" \
            ${DOWNSTREAM_NAME}-${VERSION}/utils/sccli.py \
            -e "s|^IMAGE_NAME =\(\s\+\)\(.*\)$ |IMAGE_NAME = \"openshift3/ose\"|" \
            -e "s|^IMAGE_TAG =\(\s\+\)\(.*\)$ |IMAGE_TAG = \"${DOWNSTREAM_IMAGE_VERSION}\"|"
```

Comments?

**Comment by praveenkumar** [comment]
@LalatenduMohanty  that's what we should do but still kickstart file have version info by which we are going to build our boxes and set option there to `openshift_options` file. 

Case is assume user forget any version info in CDK vagrantfile then then it will fetch latest and our cached files have no use of it.

**Comment by LalatenduMohanty** [comment]
> Case is assume user forget any version info in CDK vagrantfile then then it will fetch latest and our cached files have no use of it.

For cached OSE images openshift_options file should have the same version.

**Comment by LalatenduMohanty** [comment]
And the [Makefile](https://github.com/projectatomic/adb-utils/blob/master/Makefile) would have the information required for downstream which will be used during builds.

**Comment by praveenkumar** [comment]
> And the Makefile would have the information required for downstream which will be used during builds.

Then Makefile and https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/build_tools/kickstarts/rhel-7-cdk-vagrant.ks#L199 tag suppose to same which will add one more point to add when we do any build. but if we just update openshift_option in kickstart file not in the makefile according to tag then only single patch will be enough in future.

**Comment by LalatenduMohanty** [comment]
@praveenkumar So For CDK , we just have the cached image version information in openshift_options, no where else.

**Comment by praveenkumar** [comment]
> So For CDK , we just have the cached image version information in openshift_options, no where else.

And in the kickstart file which version we are going to cached. so information is at 2 different places `openshift_options => adb-utils repo` and `kickstart => adb-developer-bundle repo` so my opinion is to have it on single place.

**Comment by LalatenduMohanty** [comment]
> so my opinion is to have it on single place.

Agree. We need the KS file change

**Comment by praveenkumar** [comment]
@LalatenduMohanty @bexelbie so we all agree to have it in single place and decide it in KS file so I think https://github.com/projectatomic/adb-atomic-developer-bundle/pull/402 make sense now only have to remove `sccli` bits from it.

**Comment by bexelbie** [comment]
@LalatenduMohanty @praveenkumar I've read this several times and I am feel like I am missing something.  I believe the OS[O/E] version appears in the following places:
1. Kickstart
2. sccli
3. Vagrantfile
4. openshift_options file

What exactly are you proposing be put into each.  Which files would need to be modified to change the default OS[O/E] version in a future ADB?

**Comment by praveenkumar** [comment]
@bexelbie Only in kickstart file and Vagrantfile other places we should have `latest`.

**Comment by LalatenduMohanty** [comment]
And SCCLI will not have any version.

**Comment by bexelbie** [comment]
> And SCCLI will not have any version.

Then what happens if you run `sccli` that was installed via `yum install adb-utils` and not one that was built into the ADB?

**Comment by LalatenduMohanty** [comment]
@praveenkumar Also for ADB we don't need the kickstart file change as openshift_options will have latest and Vagrantfile will have the curated version.

**Comment by LalatenduMohanty** [comment]
> Then what happens if you run sccli that was installed via yum install adb-utils and not one that was built into the ADB?

It should work fine. As it gets the value from openshift_options or environment.

**Comment by bexelbie** [comment]
> @praveenkumar Also for ADB we don't need the kickstart file change as openshift_options will have latest and Vagrantfile will have the curated version.

Won't this cause the bug where starting openshift with sccli in the box gets a different version from what is started via the Vagrantfile?  Or will sccli modify the options file so it can "take notes" on what version should now be default?

> > Then what happens if you run sccli that was installed via yum install adb-utils and not one that was built into the ADB?
> 
> It should work fine. As it gets the value from openshift_options or environment.

Where are you setting the openshift_options value?

**Comment by praveenkumar** [comment]
> Or will sccli modify the options file so it can "take notes" on what version should now be default?

So till now we are defining defaults to sccli itself instead of that it will take defaults from `openshift_options` file.

> Where are you setting the openshift_options value?

`openshift_options` sets in the kickstart file for specific tag version.

**Comment by bexelbie** [comment]
@praveenkumar will you be putting in a PR to adb-utils to set up a `latest` default for openshift_options as a one-time modification?

**Comment by praveenkumar** [comment]
> @praveenkumar will you be putting in a PR to adb-utils to set up a latest default for openshift_options as a one-time modification?

I will ask lala to update this PR with whatever changes we discuss and then I will update https://github.com/projectatomic/adb-atomic-developer-bundle/pull/402 , sound good?

**Comment by LalatenduMohanty** [comment]
Closing this in favor of #133

**Pull request closed without merging**
