### PR TITLE
Setup CONTRIBUTING & MAINTAINERS docs

### PR DESCRIPTION
**Pull request by bexelbie**

### CODE REVIEW

**Comment by praveenkumar** [comment]
LGTM

**Comment by LalatenduMohanty** [comment]
@navidshaikh Need your acknowledgment ( before merging) as you are being added as a maintainers. Otherwise LGTM

**Comment by praveenkumar** [comment]
@LalatenduMohanty 2 ACK is enough from maintainer and since bex also maintainer so this PR actually got 3 ACKs :). Merging it now.

**Comment by LalatenduMohanty** [comment]
@praveenkumar I think you did not get my point. I was asking @navidshaikh if he is interested to become the maintainer or not

**Comment by navidshaikh** [comment]
LGTM! :-)

**Pull request merged**
