### PR TITLE
Issue #82 Adjusting the corsAllowedOrigins value of master-config.yam…

### PR DESCRIPTION
**Pull request by hferentschik**
…l to allow cross-origin resource sharing

### CODE REVIEW

**Comment by praveenkumar** [comment]
Thank you for your patch contribution. 

LGTM

**Comment by hferentschik** [comment]
Thanks :-)

**Comment by hferentschik** [comment]
BTW, it would probably make sense to add some sentences about Swagger usage to the docs. How does one do that? Where are the sources for the docs?

**Comment by hferentschik** [comment]
Also, on a different note, do you guys really like merge commits? In the teams I was working before, we always favored strictly linear history and made sure to apply only fast forward patches. For that reason we for example also never merged via the Git web UI, since it will always add a merge commit, even if the pull request otherwise is a fast forward. IMO strictly linear history is easier to read. There is just less noise. Just wondering.

**Comment by praveenkumar** [comment]
> Also, on a different note, do you guys really like merge commits? In the teams I was working before, we always favored strictly linear history and made sure to apply only fast forward patches. For that reason we for example also never merged via the Git web UI, since it will always add a merge commit, even if the pull request otherwise is a fast forward. IMO strictly linear history is easier to read. There is just less noise. Just wondering.

Yes we are using Git web UI to merge a PR. I know it's not make history easier to read but currently this is the process and in future we might change to strictly solution.

**Pull request merged**
